import { type } from "os"

// action types
export const FETCH_ROCKETS_SUCCESS = 'spacex/FETCH_ROCKETS_SUCCESS'
export type FETCH_ROCKETS_SUCCESS = typeof FETCH_ROCKETS_SUCCESS

export const FETCH_ROCKETS_REQUEST = 'spacex/FETCH_ROCKETS_REQUEST'
export type FETCH_ROCKETS_REQUEST = typeof FETCH_ROCKETS_REQUEST

export const FETCH_ROCKETS_FAIL = 'spacex/FETCH_ROCKETS_FAIL'
export type FETCH_ROCKETS_FAIL = typeof FETCH_ROCKETS_FAIL

export const FETCH_SINGLE_ROCKET_SUCCESS = 'spacex/FETCH_SINGLE_ROCKET_SUCCESS'
export type FETCH_SINGLE_ROCKET_SUCCESS = typeof FETCH_SINGLE_ROCKET_SUCCESS

export const FETCH_SINGLE_ROCKET_REQUEST = 'spacex/FETCH_SINGLE_ROCKET_REQUEST'
export type FETCH_SINGLE_ROCKET_REQUEST = typeof FETCH_SINGLE_ROCKET_REQUEST

export const FETCH_SINGLE_ROCKET_FAIL = 'spacex/FETCH_SINGLE_ROCKET_FAIL'
export type FETCH_SINGLE_ROCKET_FAIL = typeof FETCH_SINGLE_ROCKET_FAIL
